# -*- coding: utf-8 -*-
"""Futureintern_DA_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhVxs9YRaCE6qPi35C6Y9ViKHSlTB1Se
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

#load the Iris dataset
iris = pd .read_csv('Iris.csv')

iris.head()

#select the feater you want to visualize
feature_to_plot="SepalLengthCm"

#create histogram SepalLengthCm
plt.figure(figsize=(8, 6))
sns.histplot(iris[feature_to_plot], kde=True, color ="blue")
plt.title('Hidtogram of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("Frequency")
plt.show()

#select the feater you want to visualize
feature_to_plot="SepalWidthCm"

#create histogram SepalWidthCm
plt.figure(figsize=(8, 6))
sns.histplot(iris[feature_to_plot], kde=True, color ="blue")
plt.title('Hidtogram of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("Frequency")
plt.show()

#select the feater you want to visualize
feature_to_plot="PetalLengthCm"

#create histogram PetalLengthCm
plt.figure(figsize=(8, 6))
sns.histplot(iris[feature_to_plot], kde=True, color ="blue")
plt.title('Hidtogram of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("Frequency")
plt.show()

#select the feater you want to visualize
feature_to_plot="PetalWidthCm"

#create histogram PetalWidthCm
plt.figure(figsize=(8, 6))
sns.histplot(iris[feature_to_plot], kde=True, color ="blue")
plt.title('Hidtogram of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("Frequency")
plt.show()

#select the feater you want to visualize
feature_to_plot="Species"

#create histogram Species
plt.figure(figsize=(8, 6))
sns.histplot(iris[feature_to_plot], kde=True, color ="blue")
plt.title('Hidtogram of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("Frequency")
plt.show()

#select the feater you want to visualize
feature_to_plot="SepalLengthCm"

#create histogram SepalLengthCm
plt.figure(figsize=(8, 6))
iris[feature_to_plot]. value_counts().plot(kind="bar" , color="green")
plt.title('Bar chart of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("count")
plt.xticks(rotation=45)
plt.show()

#select the feater you want to visualize
feature_to_plot="SepalWidthCm"

#create histogram SepalWidthCm
plt.figure(figsize=(8, 6))
iris[feature_to_plot]. value_counts().plot(kind="bar" , color="green")
plt.title('Bar chart of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("count")
plt.xticks(rotation=45)
plt.show()

#select the feater you want to visualize
feature_to_plot="PetalLengthCm"

#create histogram PetalLengthCm
plt.figure(figsize=(8, 6))
iris[feature_to_plot]. value_counts().plot(kind="bar" , color="green")
plt.title('Bar chart of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("count")
plt.xticks(rotation=45)
plt.show()

#select the feater you want to visualize
feature_to_plot="PetalWidthCm"

#create histogram PetalWidthCm
plt.figure(figsize=(8, 6))
iris[feature_to_plot]. value_counts().plot(kind="bar" , color="green")
plt.title('Bar chart of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("count")
plt.xticks(rotation=45)
plt.show()

#select the feater you want to visualize
feature_to_plot="Species"

#create histogram Species
plt.figure(figsize=(8, 6))
iris[feature_to_plot]. value_counts().plot(kind="bar" , color="green")
plt.title('Bar chart of {feature_to_plot} in Iris Dataset')
plt.xlabel(feature_to_plot)
plt.ylabel("count")
plt.xticks(rotation=45)
plt.show()

fig ,ax =plt.subplots(ncols=2, figsize=(16,4))
sns.scatterplot(iris, x='SepalLengthCm',y='SepalWidthCm',hue='Species',ax=ax[0])
sns.scatterplot(iris, x='PetalLengthCm',y='PetalWidthCm',hue='Species',ax=ax[1])

